# Generated by Django 5.2.15 on 2026-06-28 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_summary', models.TextField()),
                ('emails_processed', models.PositiveIntegerField(default=0)),
                ('last_refreshed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='clients.client')),
            ],
            options={
                'db_table': 'email_summaries',
            },
        ),
    ]
