# Generated by Django 5.2.15 on 2026-06-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
