# Generated by Django 6.0.6 on 2026-06-29 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='firms.firm'),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('FIRM_ADMIN', 'Firm Admin'), ('ACCOUNTANT', 'Accountant')], default='ACCOUNTANT', max_length=20),
        ),
    ]
