# Generated by Django 6.0.6 on 2026-06-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_firm_alter_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('ACCOUNTANT', 'Accountant'), ('CLIENT', 'Client')], default='CLIENT', max_length=20),
        ),
    ]
