# Generated by Django 6.0.6 on 2026-06-30 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firm',
            options={'ordering': ['name'], 'verbose_name': 'Firm', 'verbose_name_plural': 'Firms'},
        ),
    ]
