import os
import json
import google.generativeai as genai


def mock_summary(emails):
    """
    Generate a basic summary from email data without using an AI model.

    This function extracts:
    - Unique actors (accountant email addresses)
    - Concluded discussions based on simple keyword matching
    - Open action items for remaining emails

    Args:
        emails (QuerySet): Collection of Email model instances.

    Returns:
        dict: Summary containing actors, concluded discussions,
        and open action items.
    """
    actors = set()
    open_items = []
    concluded = []

    for email in emails:
        actors.add(email.accountant.email)

        body = email.body.lower()

        if "received" in body or "thank you" in body:
            concluded.append(email.subject)
        else:
            open_items.append(email.subject)

    return {
        "actors": list(actors),
        "concluded_discussions": concluded,
        "open_action_items": open_items,
    }


def gemini_summary(emails_text):
    """
    Generate an email summary using the Google Gemini API.

    The function sends the combined email text to the Gemini model
    and requests a structured JSON response containing:
    - Actors
    - Concluded discussions
    - Open action items

    Any markdown formatting returned by the model is removed before
    parsing the JSON response.

    Args:
        emails_text (str): Combined email subject and body text.

    Returns:
        dict: Parsed JSON summary generated by Gemini.
    """
    genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
    model = genai.GenerativeModel("gemini-1.5-flash")

    prompt = f"""
You are an AI assistant summarizing email threads.

Extract JSON with:
- actors
- concluded_discussions
- open_action_items

Emails:
{emails_text}

Return ONLY valid JSON. No markdown, no explanation.
"""

    response = model.generate_content(prompt)

    text = response.text.strip()

    # Clean possible markdown formatting
    if "```" in text:
        text = text.replace("```json", "").replace("```", "").strip()

    return json.loads(text)


def generate_summary(emails):
    """
    Generate an email summary using the configured summarization strategy.

    If a valid Gemini API key is available, the function attempts to
    generate the summary using the Gemini model. If the API call fails
    or no API key is configured, it falls back to the mock summary
    implementation.

    Args:
        emails (QuerySet): Collection of Email model instances.

    Returns:
        dict: Structured email summary containing actors,
        concluded discussions, and open action items.
    """
    emails_text = "\n".join(
        [f"{e.subject}: {e.body}" for e in emails]
    )

    if os.getenv("GEMINI_API_KEY") and os.getenv("GEMINI_API_KEY").strip():
        try:
            return gemini_summary(emails_text)
        except Exception:
            # Fall back to mock summary if Gemini API fails
            return mock_summary(emails)

    return mock_summary(emails)