### Login
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
    "email": "akash.dayma@thoughtwin.com",
    "password": "aakash@123"
}

###

### Copy the ACCESS token from the login response
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgyNzI0MTg2LCJpYXQiOjE3ODI3MjIzODYsImp0aSI6IjNjYmJkNWQxYjE1YjQ5MmQ4MjNjNWJkODY4ZmM4YjVkIiwidXNlcl9pZCI6IjMifQ.OpsxeBQbY37eyV-8sOOnhARUaSoR1X6nsGUpsgomO18

### Get Clients
GET http://127.0.0.1:8000/api/clients/
Authorization: Bearer {{token}}

###

### Get Client Detail
GET http://127.0.0.1:8000/api/clients/1/
Authorization: Bearer {{token}}

###

### Get Emails
GET http://127.0.0.1:8000/api/1/emails/
Authorization: Bearer {{token}}

###

### Generate Summary
POST http://127.0.0.1:8000/api/1/summary/
Authorization: Bearer {{token}}

###

### Refresh Summary
POST http://127.0.0.1:8000/api/1/summary/refresh/
Authorization: Bearer {{token}}

###

### Firm Report
GET http://127.0.0.1:8000/api/reports/api/
Authorization: Bearer {{token}}

###

### Global Report
GET http://127.0.0.1:8000/api/reports/api/global/
Authorization: Bearer {{token}}