# Generated by Django 6.0.6 on 2026-06-30 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='accountants',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'ACCOUNTANT'}, related_name='assigned_clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
