# Generated by Django 5.2.15 on 2026-06-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
