# Generated by Django 6.0.6 on 2026-06-30 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_email_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AlterField(
            model_name='email',
            name='accountant',
            field=models.ForeignKey(limit_choices_to={'role': 'ACCOUNTANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL),
        ),
    ]
